### ISSUE TITLE
Display times in am/pm

### ISSUE THREAD

**Issue by colemarkham** [eclipsesource/tabris-con#28]
Those of us in the US would l prefer to see times formatted as am/pm instead of 24-hour. It would be best to use the system locale, but a preference within the app would work as well.

**Comment by cpetrov** [comment]
Hello @colemarkham, thank you for opening this issue.

I've tried configuring Moment.js to display locally formatted times using the device's locale setting. However this only works with a side effect as Moment.js locale setting consists of coupled language and region settings. Using this setting would result into inconsistent languages of app UI and date strings when the device language is set to a language other than English.

I've provided a setting in config.js instead for a more consistent experience.
