### ISSUE TITLE
Voting '0' was not obvious

### ISSUE THREAD

**Issue by irbull** [eclipsesource/tabris-con#32]
Many people missed the fact that you could vote '0' for a talk. Furthermore, once you select :+1: or :-1: you could not unselect it. We should have an explicit '0'.

**Comment by cpetrov** [comment]
Added a neutral option for voting. The icons are faces and not thumbs anymore (faces are often used in evaluation interfaces and a neutral option can be hardly described using a hand).

![Simulator Screen Shot - iPhone 6s - 2019-09-09 at 22 51 31](https://user-images.githubusercontent.com/2341769/64541697-e8ebec80-d354-11e9-816b-21a10baae395.png)


Customization for the Eclipse community:

![Simulator Screen Shot - iPhone 6s - 2019-09-09 at 22 51 10](https://user-images.githubusercontent.com/2341769/64541741-fdc88000-d354-11e9-91bf-4b1b3608496d.png)
